# Generated by Django 5.1.6 on 2025-03-26 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_question_options_remove_question_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice1_signs',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice2_signs',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice3_signs',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice4_signs',
        ),
        migrations.AddField(
            model_name='question',
            name='choice1_signs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice1_questions', to='app.roadsign', verbose_name='Choice 1 Signs'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2_signs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice2_questions', to='app.roadsign', verbose_name='Choice 2 Signs'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3_signs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice3_questions', to='app.roadsign', verbose_name='Choice 3 Signs'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4_signs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice4_questions', to='app.roadsign', verbose_name='Choice 4 Signs'),
        ),
    ]
