# Generated by Django 5.1.6 on 2025-03-26 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_question_choice1_signs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='app.roadsign', verbose_name='Question Image'),
        ),
    ]
