# Generated by Django 5.1.6 on 2025-03-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userexamanswer_selected_choice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.IntegerField(default=1),
        ),
    ]
