# Generated by Django 5.1.6 on 2025-04-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_subscription_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledexam',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='active_subscription',
        ),
    ]
