# Generated by Django 5.1.6 on 2025-04-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_scheduledexam_updated_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsign',
            name='name',
            field=models.CharField(default='Ibimenyetso', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
