# Generated by Django 5.1.6 on 2025-04-02 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_roadsign_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ibivanze', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.examtypes'),
        ),
    ]
