# Generated by Django 5.1.6 on 2025-04-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_examtypes_remove_exam_title_exam_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
    ]
