# Generated by Django 5.1.5 on 2025-02-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration_days',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(default=25078, max_length=13),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
