# Generated by Django 5.1.5 on 2025-02-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_plan_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('upload_time', models.DateTimeField(help_text='When should this exam be published?')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
