# Generated by Django 5.1.5 on 2025-02-07 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scheduledexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledexam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scheduledexam',
            name='title',
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='app.exam'),
        ),
    ]
