# Generated by Django 5.1.5 on 2025-02-08 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_scheduledexam_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexam',
            name='scheduled_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date & time when the exam should be published'),
            preserve_default=False,
        ),
    ]
