# Generated by Django 5.1.5 on 2025-02-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_scheduledexam_scheduled_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledexam',
            name='upload_time',
        ),
        migrations.AlterField(
            model_name='scheduledexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam'),
        ),
    ]
