# Generated by Django 5.1.5 on 2025-02-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notification_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='mwami', max_length=16),
            preserve_default=False,
        ),
    ]
