# Generated by Django 5.1.5 on 2025-02-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(default='25078', max_length=13),
        ),
    ]
