# Generated by Django 5.1.5 on 2025-02-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_subscription_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
