# Generated by Django 5.1.5 on 2025-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.PositiveIntegerField(default=20, help_text='Duration of the exam in minutes'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order of the question in the exam'),
            preserve_default=False,
        ),
    ]
