# Generated by Django 5.1.5 on 2025-02-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_exam_duration_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
