# Generated by Django 5.1.5 on 2025-02-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_exam_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='choice_questions', to='app.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sign',
            field=models.ManyToManyField(blank=True, related_name='road_sign_questions', to='app.roadsign'),
        ),
    ]
