# Generated by Django 5.1.5 on 2025-02-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofile_gender_alter_userprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='images/'),
        ),
    ]
