# Generated by Django 5.1.6 on 2025-03-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.ForeignKey(limit_choices_to=models.Q(('id__in', models.F('choices'))), on_delete=django.db.models.deletion.CASCADE, related_name='correct_for_questions', to='app.choice'),
        ),
    ]
