# Generated by Django 5.1.6 on 2025-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sign',
        ),
        migrations.AddField(
            model_name='question',
            name='choice1_signs',
            field=models.ManyToManyField(blank=True, related_name='choice1_questions', to='app.roadsign', verbose_name='Choice 1 Signs'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice1_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Choice 1 Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2_signs',
            field=models.ManyToManyField(blank=True, related_name='choice2_questions', to='app.roadsign', verbose_name='Choice 2 Signs'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Choice 2 Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3_signs',
            field=models.ManyToManyField(blank=True, related_name='choice3_questions', to='app.roadsign', verbose_name='Choice 3 Signs'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Choice 3 Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4_signs',
            field=models.ManyToManyField(blank=True, related_name='choice4_questions', to='app.roadsign', verbose_name='Choice 4 Signs'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Choice 4 Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_choice',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3'), (4, 'Choice 4')], default=1, verbose_name='Correct Choice Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Question Text'),
        ),
    ]
