# Generated by Django 5.1.6 on 2025-03-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_choice_date_added_alter_choice_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_for_questions', to='app.choice'),
        ),
    ]
