# Generated by Django 5.1.6 on 2025-03-24 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_question_correct_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsign',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadsign',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roadsign',
            name='sign_image',
            field=models.FileField(upload_to='road_signs/'),
        ),
        migrations.AlterField(
            model_name='roadsign',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.signtype'),
        ),
    ]
