# Generated by Django 5.1.5 on 2025-02-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Gabo'), ('female', 'Gore')], max_length=10, null=True),
        ),
    ]
