# Generated by Django 5.1.6 on 2025-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_question_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1_text',
            field=models.CharField(blank=True, max_length=700, verbose_name='Choice 1 Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Choice 2 Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Choice 3 Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Choice 4 Text'),
        ),
    ]
