# Generated by Django 5.1.6 on 2025-03-24 13:59

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_roadsign_date_added_roadsign_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roadsign',
            name='sign_image',
            field=models.ImageField(upload_to='road_signs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp'])]),
        ),
    ]
