# Generated by Django 5.1.6 on 2025-02-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Daily', 'Umunsi'), ('Weekly', 'Icyumweru'), ('Monthly', 'Ukwezi'), ('Super', 'Rihoraho')], default='Daily', max_length=10, null=True),
        ),
    ]
