# Generated by Django 5.1.6 on 2025-03-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_question_choice1_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexamanswer',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice1_signs',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice2_signs',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice3_signs',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice4_signs',
        ),
        migrations.AddField(
            model_name='question',
            name='choice1_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice1_questions', to='app.roadsign', verbose_name='Choice 1 Sign'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice2_questions', to='app.roadsign', verbose_name='Choice 2 Sign'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice3_questions', to='app.roadsign', verbose_name='Choice 3 Sign'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice4_questions', to='app.roadsign', verbose_name='Choice 4 Sign'),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='selected_choice_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3'), (4, 'Choice 4')], default=1, verbose_name='Selected Choice Number'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
