# Generated by Django 5.1.6 on 2025-03-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_question_date_added_question_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadsign',
            old_name='date_added',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='roadsign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
