# Generated by Django 5.1.6 on 2025-03-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_plan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Daily', "Ry'umunsi"), ('Weekly', "Ry'icyumweru"), ('Monthly', "Ry'ukwezi"), ('Super', 'Rihoraho')], default='Daily', max_length=10, null=True),
        ),
    ]
