# Generated by Django 5.1.6 on 2025-03-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userexamanswer_selected_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexamanswer',
            name='selected_choice_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3'), (4, 'Choice 4')], null=True, verbose_name='Selected Choice Number'),
        ),
    ]
