# Generated by Django 5.1.6 on 2025-03-24 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_date_added_roadsign_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsign',
            name='definition',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='roadsign',
            name='sign_image',
            field=models.ImageField(unique=True, upload_to='road_signs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp'])]),
        ),
    ]
