# Generated by Django 5.1.6 on 2025-03-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_plan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, unique=True),
        ),
    ]
