# Generated by Django 5.1.6 on 2025-03-24 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_roadsign_definition_alter_roadsign_sign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsign',
            name='sign_image',
            field=models.ImageField(upload_to='road_signs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp'])]),
        ),
    ]
