# Generated by Django 5.1.6 on 2025-04-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_subscription_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledexam',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='active_subscription',
        ),

        migrations.CreateModel(
            name="ExamType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Ibivanze", max_length=500)),
            ],
        ),

        migrations.AddField(
            model_name="scheduledexam",
            name="updated_datetime",
            field=models.DateTimeField(
                auto_now=True, help_text="Date & time when the exam should be published"
            ),
        ),
        migrations.AlterField(
            model_name="userexam",
            name="completed_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
