# Generated by Django 5.1.6 on 2025-03-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_roadsign_sign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Order of the question in the exam', null=True),
        ),
    ]
