# Generated by Django 5.1.6 on 2025-03-23 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_signtype_alter_userprofile_name_alter_roadsign_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
