# Generated by Django 5.1.6 on 2025-04-02 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_scheduledexam_is_published_and_more"),
    ]

    operations = [


        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="app.examtype",
            ),
        ),
    ]
