# Generated by Django 5.1.6 on 2025-04-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_scheduledexam_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexam',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='Date & time when the exam should be published'),
        ),
    ]
