# Generated by Django 5.1.6 on 2025-04-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='for_scheduling',
            field=models.BooleanField(default=True),
        ),
    ]
