# Generated by Django 5.1.6 on 2025-04-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_exam_for_scheduling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_end_date',
        ),
    ]
