# Generated by Django 5.1.6 on 2025-04-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ("app", "0012_remove_userprofile_subscription_end_date"),
    ]

    operations = []
