# Generated by Django 5.1.6 on 2025-04-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_exam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='order',
            field=models.IntegerField(default=5),
        ),
    ]
