# Generated by Django 5.1.6 on 2025-04-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.examtypes'),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
