# Generated by Django 5.1.6 on 2025-04-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_examtype_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examtype', verbose_name='Question Type'),
        ),
    ]
