# Generated by Django 5.1.6 on 2025-04-04 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledexam',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.exam'),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
