# Generated by Django 5.1.6 on 2025-04-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_scheduledexam_exam_alter_userexam_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Display Order'),
        ),
    ]
