# Generated by Django 5.1.6 on 2025-04-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='04.04.2025 18', max_length=100),
        ),
    ]
