# Generated by Django 5.1.6 on 2025-04-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Display Order'),
        ),
    ]
