# Generated by Django 5.1.6 on 2025-04-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_question_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(default="04.04.2025 19", max_length=100),
        ),
    ]
