# Generated by Django 5.1.6 on 2025-04-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='super_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='06.04.2025 10', max_length=100),
        ),
    ]
