# Generated by Django 5.1.6 on 2025-04-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_exam_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(default="05.04.2025 16", max_length=100),
        ),
    ]
