# Generated by Django 5.1.6 on 2025-04-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_subscription_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='06.04.2025 11', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
