# Generated by Django 5.1.6 on 2025-04-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_exam_name"),
        ("app", "0023_alter_exam_name_alter_subscription_duration_days_and_more"),
    ]

    operations = []
