# Generated by Django 5.1.6 on 2025-04-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_merge_20250406_1353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(default="06.04.2025 11", max_length=100),
        ),
    ]
