# Generated by Django 5.1.6 on 2025-04-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='10.04.2025 07', max_length=100),
        ),
    ]
