# Generated by Django 5.1.6 on 2025-04-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='10.04.2025 10', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Daily', "Ry'umunsi"), ('Weekly', "Ry'icyumweru"), ('Monthly', "Ry'ukwezi")], default='Daily', max_length=10, null=True),
        ),
    ]
