# Generated by Django 5.1.6 on 2025-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_exam_name_alter_plan_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(default="10.04.2025 13", max_length=100),
        ),
    ]
