# Generated by Django 5.1.6 on 2025-04-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='10.04.2025 19', max_length=100),
        ),
    ]
