# Generated by Django 5.1.6 on 2025-04-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_userprofile_gender_alter_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
