# Generated by Django 5.1.6 on 2025-04-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='schedule_hour',
            field=models.TimeField(blank=True, help_text='Hour when the exam should be published', null=True),
        ),
    ]
