# Generated by Django 5.1.6 on 2025-04-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_exam_schedule_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
    ]
