# Generated by Django 5.1.6 on 2025-04-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_exam_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayExam',
            fields=[
            ],
            options={
                'verbose_name': 'Exam for Today',
                'verbose_name_plural': 'Exams Of Today',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.scheduledexam',),
        ),
        migrations.CreateModel(
            name='UnscheduledExam',
            fields=[
            ],
            options={
                'verbose_name': 'Exam By Type',
                'verbose_name_plural': 'Exams By Types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.exam',),
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'User Messages'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exam', 'verbose_name_plural': 'All Exams'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'User Notification', 'verbose_name_plural': 'User Notifications'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'User Payment', 'verbose_name_plural': 'User Payments'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'All Accounts'},
        ),
    ]
