# Generated by Django 5.1.6 on 2025-04-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_todayexam_unscheduledexam_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userexam",
            options={"ordering": ["-completed_at"]},
        ),
    ]
