# Generated by Django 5.1.6 on 2025-04-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_userprofile_whatsapp_consent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="started_at",
            field=models.DateField(auto_now=True),
        ),
    ]
