# Generated by Django 5.1.6 on 2025-04-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_subscription_updated_subscription_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
