# Generated by Django 5.1.6 on 2025-04-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='delta_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='delta_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
