# Generated by Django 5.1.6 on 2025-04-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_plan_delta_days_plan_delta_hours_plan_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Daily', "Ry'umunsi"), ('Weekly', "Ry'icyumweru"), ('Monthly', "Ry'ukwezi")], max_length=20, unique=True),
        ),
    ]
