# Generated by Django 5.1.6 on 2025-05-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_plan_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='delta_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delta_hours',
            field=models.IntegerField(default=0),
        ),
    ]
