# Generated by Django 5.1.6 on 2025-05-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_subscription_delta_days_subscription_delta_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="duration_days",
        ),
    ]
