# Generated by Django 5.1.6 on 2025-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_subscription_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Hourly', "Ry'isaha"), ('Daily', "Ry'umunsi"), ('Weekly', "Ry'icyumweru"), ('Monthly', "Ry'ukwezi"), ('Super', 'Super')], max_length=20, unique=True),
        ),
    ]
