# Generated by Django 5.1.6 on 2025-05-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_plan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Hourly', "Ry'isaha"), ('Daily', "Ry'umunsi"), ('VIP', 'VIP')], max_length=20, unique=True),
        ),
    ]
