# Generated by Django 5.1.6 on 2025-05-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_plan_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='duration_days',
        ),
        migrations.AlterField(
            model_name='plan',
            name='delta_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='delta_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
