# Generated by Django 5.1.6 on 2025-06-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_contactmessage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Hourly', "Ry'isaha"), ('Half-Day', "Ry'amasaha 12"), ('Daily', "Ry'umunsi"), ('VIP', 'VIP')], max_length=20, unique=True),
        ),
    ]
