# Generated by Django 5.1.6 on 2025-07-21 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_plan_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('Video', 'Video'), ('Text', 'Text')], default='Video', max_length=100)),
                ('description', models.TextField()),
                ('course_file', models.FileField(unique=True, upload_to='courses/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'mp4', 'avi', 'mkv'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
