# Generated by Django 5.1.6 on 2025-07-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exams_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.examtype'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Video', 'Video'), ('Isomo ryanditse', 'Isomo ryanditse')], default='Video', max_length=100),
        ),
    ]
