# Generated by Django 5.1.6 on 2025-07-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_course_exams_type_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='icon',
            field=models.CharField(blank=True, help_text="Bootstrap icon class name (e.g., 'bi bi-journal-text')", max_length=50, null=True),
        ),
    ]
