# Generated by Django 5.1.6 on 2025-07-22 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Ibibisobanuro by'isomo", null=True),
        ),
    ]
