# Generated by Django 5.1.6 on 2025-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Hourly', 'Isaha'), ('Half-Day', 'Amasaha 12'), ('Daily', 'Umunsi'), ('Weekly', 'IBYUMWERU 2'), ('VIP', 'VIP')], max_length=20, unique=True),
        ),
    ]
