# Generated by Django 5.1.6 on 2025-10-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_paymentconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfirm',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
