# Generated by Django 5.1.6 on 2025-10-08 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_paymentconfirm_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfirm',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
