# Generated by Django 5.1.6 on 2025-10-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_rec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(choices=[('Hourly', 'Isaha'), ('Half-Day', 'Amasaha 12'), ('Weekly', 'Icyumweru'), ('Half-Month', 'Iminsi 15'), ('VIP', 'VIP')], max_length=20, unique=True),
        ),
    ]
