# Generated by Django 5.1.6 on 2025-10-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_plan_is_rec_alter_plan_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED_PASSWORD', 'Failed Password'), ('FAILED_NO_PRIVILEGES', 'No Staff Privileges'), ('FAILED_INACTIVE', 'Account Inactive'), ('FAILED_SUSPICIOUS', 'Suspicious Activity'), ('FAILED_NOT_EXIST', 'Account Not Exist')], max_length=20)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_login_attempts',
                'indexes': [models.Index(fields=['username', 'attempted_at'], name='staff_login_usernam_003f3e_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='staff_login_ip_addr_84db28_idx')],
            },
        ),
    ]
