# Generated by Django 5.1.6 on 2025-11-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_staffloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
