# Generated by Django 5.1.6 on 2026-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0067_subscription_otp_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
