# Generated by Django 5.1.6 on 2026-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0069_alter_subscription_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAutoConfirmSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable automatic payment confirmation"
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        help_text="Start of the period when auto-confirmation is active"
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        help_text="End of the period when auto-confirmation is active"
                    ),
                ),
                (
                    "required_confirms",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Number of payment confirms required to auto-confirm (default: 2)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Auto-Confirm Setting",
                "verbose_name_plural": "Payment Auto-Confirm Settings",
            },
        ),
        migrations.AlterField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
