# Generated by Django 5.1.6 on 2026-02-23 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0070_paymentautoconfirmsetting_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentConfirmLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_confirm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.paymentconfirm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Confirm Log",
                "verbose_name_plural": "Payment Confirm Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
