# Generated by Django 5.1.6 on 2026-02-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_optimize_indexes"),
        ("app", "0071_paymentconfirmlog"),
    ]

    operations = []
