# Generated by Django 5.1.6 on 2026-03-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0072_merge_0008_optimize_indexes_0071_paymentconfirmlog"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="course",
            name="course_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="course_category_idx",
        ),
        migrations.RemoveIndex(
            model_name="exam",
            name="exam_type_scheduling_idx",
        ),
        migrations.RemoveIndex(
            model_name="exam",
            name="exam_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="exam",
            name="exam_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notification_user_read_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payment_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payment_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="question_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="question_order_idx",
        ),
        migrations.RemoveIndex(
            model_name="roadsign",
            name="roadsign_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduledexam",
            name="scheduled_datetime_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduledexam",
            name="scheduled_exam_idx",
        ),
        migrations.RemoveIndex(
            model_name="subscription",
            name="sub_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="subscription",
            name="sub_expires_idx",
        ),
        migrations.RemoveIndex(
            model_name="subscription",
            name="sub_otp_verified_idx",
        ),
        migrations.RemoveIndex(
            model_name="useractivity",
            name="activity_user_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="userexam",
            name="user_exam_idx",
        ),
        migrations.RemoveIndex(
            model_name="userexam",
            name="userexam_completed_idx",
        ),
        migrations.RemoveIndex(
            model_name="userexam",
            name="user_completed_idx",
        ),
        migrations.RemoveIndex(
            model_name="userexamanswer",
            name="answer_exam_idx",
        ),
        migrations.RemoveIndex(
            model_name="userexamanswer",
            name="answer_question_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="phone_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="email_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="active_idx",
        ),
    ]
