# Generated by Django 5.1.6 on 2026-06-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_bulkimageupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="plan",
            field=models.CharField(
                choices=[
                    ("Hourly", "Isaha"),
                    ("Daily", "Amasaha 24"),
                    ("Weekly", "Icyumweru"),
                    ("Half-Month", "Iminsi 15"),
                    ("Monthly", "Iminsi 30"),
                    ("VIP", "VIP"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
