# Generated by Django 5.1.6 on 2026-06-13 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_alter_plan_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("400", "Bad Request"),
                            ("403", "Forbidden"),
                            ("404", "Not Found"),
                            ("500", "Server Error"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message or exception details"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True,
                        help_text="The URL path where error occurred",
                        max_length=500,
                    ),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, default="GET", max_length=10),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent string"),
                ),
                (
                    "remote_address",
                    models.CharField(
                        blank=True, help_text="Client IP address", max_length=50
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        blank=True, help_text="HTTP referrer", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Notes added by admin"),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="error_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Report",
                "verbose_name_plural": "Error Reports",
                "ordering": ["-reported_at"],
                "indexes": [
                    models.Index(
                        fields=["-reported_at"], name="app_errorre_reporte_e76b5a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="app_errorre_status_b13f0c_idx"
                    ),
                    models.Index(
                        fields=["error_type"], name="app_errorre_error_t_1993b0_idx"
                    ),
                ],
            },
        ),
    ]
