# Generated by Django 5.1.6 on 2026-06-13 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_errorreport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={},
        ),
        migrations.CreateModel(
            name="TrafficLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.IntegerField(default=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "response_time",
                    models.FloatField(
                        default=0.0, help_text="Response time in milliseconds"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="traffic_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "User Messages",
            },
        ),
    ]
