# Generated by Django 5.1.6 on 2026-06-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0077_alter_contactmessage_options_trafficlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trafficlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Traffic Log",
                "verbose_name_plural": "Traffic Logs",
            },
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="browser",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="browser_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="country",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="device_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("mobile", "Mobile"),
                    ("tablet", "Tablet"),
                    ("desktop", "Desktop"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="os",
            field=models.CharField(
                choices=[
                    ("ios", "iOS"),
                    ("android", "Android"),
                    ("windows", "Windows"),
                    ("macos", "macOS"),
                    ("linux", "Linux"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="os_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="platform",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Visit"),
                    ("whatsapp", "WhatsApp"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("instagram", "Instagram"),
                    ("linkedin", "LinkedIn"),
                    ("google", "Google"),
                    ("email", "Email"),
                    ("other", "Other Referrer"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="trafficlog",
            index=models.Index(
                fields=["-timestamp"], name="app_traffic_timesta_20c16f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trafficlog",
            index=models.Index(
                fields=["path", "-timestamp"], name="app_traffic_path_f5f0a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trafficlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="app_traffic_user_id_012527_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trafficlog",
            index=models.Index(
                fields=["status_code", "-timestamp"],
                name="app_traffic_status__d5fd59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trafficlog",
            index=models.Index(
                fields=["country", "-timestamp"], name="app_traffic_country_99a55a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trafficlog",
            index=models.Index(
                fields=["device_type", "-timestamp"],
                name="app_traffic_device__eb8d6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trafficlog",
            index=models.Index(
                fields=["browser", "-timestamp"], name="app_traffic_browser_ab3944_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trafficlog",
            index=models.Index(
                fields=["os", "-timestamp"], name="app_traffic_os_8d8ee0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trafficlog",
            index=models.Index(
                fields=["platform", "-timestamp"], name="app_traffic_platfor_a05731_idx"
            ),
        ),
    ]
