"""
Django settings for mwami project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from apscheduler.triggers.cron import CronTrigger

# from django_apscheduler.jobstores import register_events, register_job



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('PROJECT_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['magpie-thorough-cicada.ngrok-free.app', '127.0.0.1']
# ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.AppConfig',
    'channels',
    'dashboard.apps.DashboardConfig',
    'django_apscheduler',
   
]

# ASGI_APPLICATION = 'mwami.routing.application'

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     },
# }

# APSCHEDULER_TASKS = {
#     'check_subscriptions': {
#         'task': 'app.subscription_checks.check_subscription_expiry',
#         'schedule': crontab(hour=0, minute=0),  # Daily at midnight
#         'replace_existing': True
#     },
# }

# Keep only this APSCHEDULER configuration
APSCHEDULER_JOBS = [
    {
        'id': 'subscription_check',
        'func': 'app.subscription_checks:check_subscription_expiry',
        'trigger': 'cron',
        'hour': 0,
        'minute': 0
    }
]


APSCHEDULER_RUN_NOW_TIMEOUT = 300  # 5 minutes
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_SAVE_EVERY_REQUEST = True

AUTH_USER_MODEL = 'app.UserProfile'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # 'app.middleware.ExamSecurityMiddleware',

]

ROOT_URLCONF = 'mwami.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.exams_slider_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'mwami.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
          'ENGINE': 'django.db.backends.mysql',  # Use the MySQL backend
          'NAME': config('DB_NAME'),                # Your database name
          'USER':   config('DB_USER'),                # Your database user
          'PASSWORD': config('DB_PASSWORD'),           # Your database password
          'HOST': config('DB_HOST'),                   # Typically 'localhost' on Windows
          'PORT': config('DB_PORT'),                        # Default MySQL port
          'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
          },
     }
}

AUTHENTICATION_BACKENDS = [
    'app.authentication.EmailOrPhoneBackend',  # Custom email/phone backend
    'django.contrib.auth.backends.ModelBackend',   # Default Django backend
]



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kigali'

USE_I18N = True

USE_TZ = True

CSRF_TRUSTED_ORIGINS = [
    'https://magpie-thorough-cicada.ngrok-free.app',  # Add your ngrok URL here
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

#for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#STRIPE_API_KEY = 'your_stripe_secret_key'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Email for production  
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


MTN_MOMO_SUBSCRIPTION_KEY = config("MTN_MOMO_SUBSCRIPTION_KEY")
MTN_MOMO_API_USER_ID = config("MTN_MOMO_API_USER_ID")
MTN_MOMO_API_KEY = config("MTN_MOMO_API_KEY")
MTN_MOMO_CALLBACK_URL = config("MTN_MOMO_CALLBACK_URL")
MTN_MOMO_COLLECTION_PRIMARY_KEY = config("MTN_MOMO_COLLECTION_PRIMARY_KEY")
MTN_MOMO_BASE_URL = config("MTN_MOMO_BASE_URL")

LOGIN_URL = 'login'